Repository GO-SOPT-GROUP5/ohouse_server, pull requests merged in 2023-05, with the labels that each got.

#4 초기 세팅, 엔티티
  src/main/java/com/cds/ohouse/common/ErrorStatus.java
  src/main/java/com/cds/ohouse/config/JpaAuditingConfig.java
  src/main/java/com/cds/ohouse/controller/GlobalExceptionHandler.java
  src/main/java/com/cds/ohouse/controller/HealthController.java
  src/main/java/com/cds/ohouse/domain/Category.java
  src/main/java/com/cds/ohouse/domain/CategoryStatus.java
  src/main/java/com/cds/ohouse/domain/CheckList.java
  src/main/java/com/cds/ohouse/domain/SubCategoryStatus.java
  src/main/java/com/cds/ohouse/domain/Tag.java
  src/main/java/com/cds/ohouse/domain/TradeState.java
  src/main/java/com/cds/ohouse/exception/BusinessLogicException.java
Labels: size/M, feat

#6 chore: category naming
  src/main/java/com/cds/ohouse/domain/CategoryStatus.java
  src/main/java/com/cds/ohouse/domain/SubCategoryStatus.java
Labels: size/S, chore

#8 매물 정보 수정 #7
  build.gradle
  src/main/java/com/cds/ohouse/common/ErrorStatus.java
  src/main/java/com/cds/ohouse/common/SuccessStatus.java
  src/main/java/com/cds/ohouse/controller/CheckListController.java
  src/main/java/com/cds/ohouse/controller/GlobalExceptionHandler.java
  src/main/java/com/cds/ohouse/domain/CheckList.java
  src/main/java/com/cds/ohouse/domain/Tag.java
  src/main/java/com/cds/ohouse/dto/request/CheckListUpdateRequestDTO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListUpdateResponseDTO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListUpdateResponseVO.java
  src/main/java/com/cds/ohouse/exception/BusinessLogicException.java
  src/main/java/com/cds/ohouse/exception/CheckListException.java
  src/main/java/com/cds/ohouse/repository/CheckListRepository.java
  src/main/java/com/cds/ohouse/service/CheckListService.java
  src/main/java/com/cds/ohouse/service/CheckListServiceImpl.java
Labels: size/M, feat

#10 카테고리 수정
  src/main/java/com/cds/ohouse/common/ErrorStatus.java
  src/main/java/com/cds/ohouse/controller/CategoryController.java
  src/main/java/com/cds/ohouse/domain/Category.java
  src/main/java/com/cds/ohouse/domain/CategoryStatus.java
  src/main/java/com/cds/ohouse/domain/CheckList.java
  src/main/java/com/cds/ohouse/dto/request/CategoryUpdateRequestDTO.java
  src/main/java/com/cds/ohouse/dto/request/CategoryUpdateRequestVO.java
  src/main/java/com/cds/ohouse/dto/request/CheckListUpdateRequestDTO.java
  src/main/java/com/cds/ohouse/repository/CategoryRepository.java
  src/main/java/com/cds/ohouse/service/CategoryService.java
  src/main/java/com/cds/ohouse/service/CategoryServiceImpl.java
Labels: size/M, feat

#14 체크리스트 삭제
  src/main/java/com/cds/ohouse/common/SuccessStatus.java
  src/main/java/com/cds/ohouse/controller/CheckListController.java
  src/main/java/com/cds/ohouse/domain/Category.java
  src/main/java/com/cds/ohouse/domain/CheckList.java
  src/main/java/com/cds/ohouse/dto/CheckListDataDTO.java
  src/main/java/com/cds/ohouse/dto/CheckListDataVO.java
  src/main/java/com/cds/ohouse/dto/request/CheckListCreateRequestDTO.java
  src/main/java/com/cds/ohouse/dto/request/CheckListCreateRequestVO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListCreateResponseDTO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListCreateResponseVO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListsGetResponseDTO.java
  src/main/java/com/cds/ohouse/repository/checkList/CheckListRepository.java
  src/main/java/com/cds/ohouse/service/CheckListService.java
  src/main/java/com/cds/ohouse/service/CheckListServiceImpl.java
Labels: size/M, feat

#16 체크리스트 조회
  src/main/java/com/cds/ohouse/common/ErrorStatus.java
  src/main/java/com/cds/ohouse/common/SuccessStatus.java
  src/main/java/com/cds/ohouse/controller/CheckListController.java
  src/main/java/com/cds/ohouse/dto/CategoryListDataDTO.java
  src/main/java/com/cds/ohouse/dto/CategoryListDataVO.java
  src/main/java/com/cds/ohouse/dto/TagDataDTO.java
  src/main/java/com/cds/ohouse/dto/request/CheckListCreateRequestDTO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListGetResponseDTO.java
  src/main/java/com/cds/ohouse/repository/CategoryRepository.java
  src/main/java/com/cds/ohouse/service/CheckListService.java
  src/main/java/com/cds/ohouse/service/CheckListServiceImpl.java
Labels: size/M, feat

#20 CORS 설정, swagger 설정
  build.gradle
  src/main/java/com/cds/ohouse/config/CorsConfig.java
  src/main/java/com/cds/ohouse/config/SwaggerConfig.java
Labels: size/XS, chore

#22 체크리스트 생성
  src/main/java/com/cds/ohouse/controller/CheckListController.java
  src/main/java/com/cds/ohouse/domain/Category.java
  src/main/java/com/cds/ohouse/domain/CheckList.java
  src/main/java/com/cds/ohouse/domain/Tag.java
  src/main/java/com/cds/ohouse/domain/TradeState.java
  src/main/java/com/cds/ohouse/dto/request/CheckListCreateRequestDTO.java
  src/main/java/com/cds/ohouse/dto/request/CheckListCreateRequestVO.java
  src/main/java/com/cds/ohouse/dto/response/CheckListCreateResponseDTO.java
  src/main/java/com/cds/ohouse/repository/CategoryRepository.java
  src/main/java/com/cds/ohouse/service/CheckListService.java
  src/main/java/com/cds/ohouse/service/CheckListServiceImpl.java
Labels: size/L, feat

#23 시간순 정렬 추가
  src/main/java/com/cds/ohouse/domain/BaseEntity.java
  src/main/java/com/cds/ohouse/domain/Category.java
  src/main/java/com/cds/ohouse/domain/CheckList.java
  src/main/java/com/cds/ohouse/domain/Tag.java
  src/main/java/com/cds/ohouse/domain/TradeState.java
  src/main/java/com/cds/ohouse/dto/request/CheckListSortType.java
  src/main/java/com/cds/ohouse/repository/checkList/CheckListRepositoryImpl.java
Labels: size/M, feat
